name: CI/CD to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build, Push Docker Image & Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg SPRING_LIQUIBASE_CONTEXTS=prod \
            --build-arg SPRING_LIQUIBASE_CHANGELOG=classpath:db/changelog/db.changelog-master-prod.yaml \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/splitora-app:1.0 .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/splitora-app:1.0

      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
